### PR TITLE
Fallback to ReadPixels(RGBA_INTEGER,INT) when user driver doesn't offer ReadPixels(RGBA_INTEGER,BYTE).

### PR DESCRIPTION
**Pull request by kdashg**
For small reads, just use INT instead of BYTE unconditionally.

### CODE REVIEW

**Comment by kdashg** [comment]
Hopefully fixes #99!

**Comment by Cloudwalk9** [comment]
By user driver, do you mean the graphics driver and it's userland libraries or something higher level? This issue occurs on Firefox and not Chromium with the same driver, in my case Nvidia 560 on Linux.

**Comment by Cloudwalk9** [comment]
Confirming this fixes just about everything, lightning even renders.

But it causes either the tab or Firefox itself to crash for me if I use Nvidia. My configuration is PRIME render offload to Nvidia on Linux driver 560.31.02, using the Flatpak version of Firefox 129. I was only able to confirm the fix on the Intel iGPU which is... not ideal for this app.

I can't say for certain if the crash is my setup, Nvidia's fault, Firefox, or anything off with my system, but it seems to happen shortly after opening the sounding graph.

**Comment by Cloudwalk9** [comment]
Confirming the crashing is Nvidia's or Firefox's fault, most likely Nvidia, nothing to do with the patch. Nvidia probably being a little shit because Firefox crashed within seconds of opening it with PRIME render offload and typing a URL.

**Comment by kdashg** [comment]
"user driver" here meaning the combination of webgl-driver-module-within-each-browser and system-driver-used-by-each-browser's-webgl-driver-module.

**Comment by niels747** [comment]
If this caused a crash on Nvidia Graphics with firefox I can't merge it like this. We would need to detect the platform and run the appropriate code

**Pull request closed without merging**
